/* Home & Living Products */

const homeProducts = [
  {
    id: "h1",
    name: "Kussensloop Satijn - 2 Stuks",
    price: 3.95,
    type: "wonenenzo",
    image: generateProductImage("Kussensloop", "ec4899"),
    features: ["Zachte Satijn", "Haarvriendelij k", "Meerdere Kleuren"],
    description: "Luxe satijnen kussensloop voor zachter haar en huid.",
    rating: 4.4,
    orders: 11234,
    discount: 50,
    originalPrice: 7.9,
    seller: "SleepWell",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "h2",
    name: "Opbergzakken Vacuüm - 5 Stuks",
    price: 6.95,
    type: "wonenenzo",
    image: generateProductImage("Opbergzakken", "06b6d4"),
    features: ["80% Ruimtebesparing", "Herbruikbaar", "5 Maten"],
    description: "Vacuüm opbergzakken voor kleding, dekbedden en kussens.",
    rating: 4.3,
    orders: 8765,
    discount: 45,
    originalPrice: 12.64,
    seller: "StoragePro",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "h3",
    name: "Douchekop met 3 Standen",
    price: 5.95,
    type: "wonenenzo",
    image: generateProductImage("Douchekop", "10b981"),
    features: ["3 Waterstralen", "Waterbesparend", "Gemakkelijk te Monteren"],
    description: "Moderne douchekop met verschillende waterstraal opties.",
    rating: 4.2,
    orders: 7654,
    discount: 55,
    originalPrice: 13.22,
    seller: "BathRoom",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "h4",
    name: "Wasmand Opvouwbaar met Handvatten",
    price: 7.49,
    type: "wonenenzo",
    image: generateProductImage("Wasmand", "f59e0b"),
    features: ["Opvouwbaar", "Stevig Canvas", "Grote Capaciteit"],
    description: "Praktische opvouwbare wasmand voor was en speelgoed.",
    rating: 4.4,
    orders: 6543,
    discount: 40,
    originalPrice: 12.48,
    seller: "HomeOrg",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "h5",
    name: "Deurmat Anti-slip Wasbaar",
    price: 4.95,
    type: "wonenenzo",
    image: generateProductImage("Deurmat", "8b5cf6"),
    features: ["Anti-slip Rug", "Machinewasbaar", "Absorberend"],
    description: "Absorberende deurmat voor binnen en buiten gebruik.",
    rating: 4.1,
    orders: 9876,
    discount: 60,
    originalPrice: 12.38,
    seller: "CleanEntry",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "h6",
    name: "Handdoekenrek Zelfklevend RVS",
    price: 6.49,
    type: "wonenenzo",
    image: generateProductImage("Handdoekenrek", "ef4444"),
    features: ["Geen Boren", "Roestvrij Staal", "Sterke Lijm"],
    description:
      "Zelfklevend handdoekenrek zonder boren, ideaal voor badkamer.",
    rating: 4.3,
    orders: 5432,
    discount: 50,
    originalPrice: 12.98,
    seller: "BathFix",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
