/* Beauty & Personal Care Products */

const beautyProducts = [
  {
    id: "b1",
    name: "Make-up Kwasten Set 12 Stuks",
    price: 5.95,
    type: "beauty",
    image: generateProductImage("Kwasten", "ec4899"),
    features: ["12 Kwasten", "Zachte Haren", "Inclusief Tasje"],
    description: "Complete professionele make-up kwasten set met opbergtasje.",
    rating: 4.5,
    orders: 18765,
    discount: 55,
    originalPrice: 13.22,
    seller: "BeautyPro",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "b2",
    name: "Gezichtsmasker Collageen - 20 Stuks",
    price: 6.95,
    type: "beauty",
    image: generateProductImage("Masker", "f59e0b"),
    features: ["20 Stuks", "Hydraterend", "Collageen & Hyaluronzuur"],
    description:
      "Verzorgende gezichtsmaskers met collageen voor een stralende huid.",
    rating: 4.3,
    orders: 14567,
    discount: 50,
    originalPrice: 13.9,
    seller: "SkinCare",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "b3",
    name: "Nagelriemen Olie Pen - 5 Stuks",
    price: 2.95,
    type: "beauty",
    image: generateProductImage("Nagelriemen", "8b5cf6"),
    features: ["5 Pennen", "Vitamine E", "Snelle Absorptie"],
    description:
      "Verzorgende nagelriemen olie pennen voor gezonde nagels en handen.",
    rating: 4.2,
    orders: 9876,
    discount: 60,
    originalPrice: 7.38,
    seller: "NailCare",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "b4",
    name: "Lipliner Set Waterproof - 12 Kleuren",
    price: 4.95,
    type: "beauty",
    image: generateProductImage("Lipliner", "ef4444"),
    features: ["12 Kleuren", "Waterproof", "Langdurig"],
    description:
      "Complete waterproof lipliner set in trending kleuren voor perfecte lippen.",
    rating: 4.4,
    orders: 11234,
    discount: 55,
    originalPrice: 11.0,
    seller: "LipBeauty",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "b5",
    name: "Wimper Curler met 10 Refills",
    price: 3.49,
    type: "beauty",
    image: generateProductImage("Wimper Curler", "06b6d4"),
    features: ["10 Reserve Pads", "Ergonomisch", "RVS Materiaal"],
    description: "Professionele wimper curler voor perfect gekrulde wimpers.",
    rating: 4.3,
    orders: 13456,
    discount: 50,
    originalPrice: 6.98,
    seller: "EyeBeauty",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "b6",
    name: "Haarborstel Ontwarrend met Massagefunctie",
    price: 3.95,
    type: "beauty",
    image: generateProductImage("Haarborstel", "10b981"),
    features: ["Ontwarrend", "Massage Noppen", "Anti-statisch"],
    description:
      "Zachte ontwarrende haarborstel met massage functie voor alle haartypes.",
    rating: 4.5,
    orders: 16789,
    discount: 60,
    originalPrice: 9.88,
    seller: "HairCare",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
