/* Toys & Games Products */

const toysProducts = [
  {
    id: "t1",
    name: "Fidget Spinners Set - 6 Stuks",
    price: 2.95,
    type: "speelgoed",
    image: generateProductImage("Fidget Spinner", "ec4899"),
    features: ["6 Verschillende Kleuren", "Anti-stress", "Stil Lagers"],
    description: "Set van 6 fidget spinners voor ontspanning en concentratie.",
    rating: 4.2,
    orders: 15678,
    discount: 60,
    originalPrice: 7.38,
    seller: "ToyWorld",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "t2",
    name: "Squishy Speeltjes Mix - 12 Stuks",
    price: 4.95,
    type: "speelgoed",
    image: generateProductImage("Squishy", "f59e0b"),
    features: ["12 Verschillende Vormen", "Zachte Textuur", "Kleurrijk"],
    description:
      "Leuke squishy speeltjes in verschillende designs voor stress relief.",
    rating: 4.4,
    orders: 12345,
    discount: 50,
    originalPrice: 9.9,
    seller: "SquishyFun",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "t3",
    name: "Pop It Fidget Toy Regenboog",
    price: 1.99,
    type: "speelgoed",
    image: generateProductImage("Pop It", "8b5cf6"),
    features: ["Siliconen", "Beide Kanten Speelbaar", "Wasbaar"],
    description: "Populaire pop it fidget toy in vrolijke regenboogkleuren.",
    rating: 4.5,
    orders: 23456,
    discount: 65,
    originalPrice: 5.69,
    seller: "PopItStore",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "t4",
    name: "Bellenblaas Set met 12 Flesjes",
    price: 3.49,
    type: "speelgoed",
    image: generateProductImage("Bellenblaas", "06b6d4"),
    features: ["12 Flesjes", "Lekkage Vrij", "Inclusief Stokjes"],
    description: "Complete bellenblaas set voor uren speelplezier buiten.",
    rating: 4.3,
    orders: 9876,
    discount: 55,
    originalPrice: 7.76,
    seller: "BubbleFun",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "t5",
    name: "Puzzel 1000 Stukjes Landschap",
    price: 5.95,
    type: "speelgoed",
    image: generateProductImage("Puzzel", "10b981"),
    features: ["1000 Stukjes", "Hoge Kwaliteit Karton", "70x50cm Afmeting"],
    description:
      "Prachtige legpuzzel met natuurlandschap voor de hele familie.",
    rating: 4.4,
    orders: 7654,
    discount: 45,
    originalPrice: 10.82,
    seller: "PuzzleWorld",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "t6",
    name: "Kaartspel Waterproof Plastic",
    price: 2.49,
    type: "speelgoed",
    image: generateProductImage("Kaartspel", "ef4444"),
    features: ["Waterproof", "Plastic PVC", "54 Kaarten"],
    description:
      "Waterdicht plastic kaartspel, perfect voor outdoor en reizen.",
    rating: 4.2,
    orders: 11234,
    discount: 60,
    originalPrice: 6.23,
    seller: "CardGames",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
