/* Kitchen Products */

const kitchenProducts = [
  {
    id: "k1",
    name: "Siliconen Keuken Spatel Set - 5 Stuks",
    price: 3.95,
    type: "keuken",
    image: generateProductImage("Spatels", "ec4899"),
    images: [
      generateProductImage("Spatels", "ec4899"),
      generateProductImage("5 Stuks", "db2777"),
      generateProductImage("In Gebruik", "be185d"),
    ],
    features: ["Hittebestendig", "Anti-aanbak", "Vaatwasserbestendig"],
    description:
      "Veelzijdige siliconen spatels in verschillende maten voor elke kookklus.",
    rating: 4.3,
    orders: 8456,
    discount: 50,
    originalPrice: 7.9,
    seller: "KitchenPlus",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "k2",
    name: "Vershouddozen Glas met Deksel - 3 Stuks",
    price: 8.95,
    type: "keuken",
    image: generateProductImage("Vershouddozen", "06b6d4"),
    images: [
      generateProductImage("Vershouddozen", "06b6d4"),
      generateProductImage("3 Maten", "0891b2"),
      generateProductImage("Met Voedsel", "0e7490"),
    ],
    features: ["BPA Vrij", "Magnetron Safe", "Luchtdicht"],
    description:
      "Praktische glazen vershouddozen voor het bewaren en verwarmen van voedsel.",
    rating: 4.5,
    orders: 6234,
    discount: 40,
    originalPrice: 14.92,
    seller: "StoreSmart",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "k3",
    name: "Kruiden Molen met Keramische Maalwerk",
    price: 4.49,
    type: "keuken",
    image: generateProductImage("Kruiden Molen", "f59e0b"),
    features: ["Verstelbare Maling", "RVS Behuizing", "Hervulbaar"],
    description:
      "Handige kruidenmolen voor vers gemalen peper, zout en andere kruiden.",
    rating: 4.2,
    orders: 5789,
    discount: 45,
    originalPrice: 8.16,
    seller: "SpiceKing",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "k4",
    name: "Thee Ei Rvs met Ketting - Set van 2",
    price: 2.95,
    type: "keuken",
    image: generateProductImage("Thee Ei", "10b981"),
    features: ["Fijne Gaas", "Gemakkelijk Schoon te Maken", "Voor Losse Thee"],
    description:
      "Handig thee ei van roestvrij staal voor het zetten van losse thee.",
    rating: 4.4,
    orders: 12345,
    discount: 55,
    originalPrice: 6.56,
    seller: "TeaTime",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "k5",
    name: "Knoflookpers met Schoonmaakborstel",
    price: 3.49,
    type: "keuken",
    image: generateProductImage("Knoflookpers", "8b5cf6"),
    features: ["Ergonomisch Design", "Inclusief Borstel", "Roestvrij Staal"],
    description:
      "Stevige knoflookpers voor het fijn persen van knoflook en gember.",
    rating: 4.1,
    orders: 4567,
    discount: 60,
    originalPrice: 8.73,
    seller: "ChefTools",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "k6",
    name: "Pannen Onderzetter Siliconen - 4 Stuks",
    price: 2.49,
    type: "keuken",
    image: generateProductImage("Onderzetters", "ef4444"),
    features: ["Hittebestendig tot 230°C", "Anti-slip", "4 Kleuren"],
    description:
      "Kleurrijke siliconen onderzetters om je tafel te beschermen tegen hete pannen.",
    rating: 4.3,
    orders: 9876,
    discount: 65,
    originalPrice: 7.11,
    seller: "TableCare",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
