/* Sports & Health Products */

const sportsProducts = [
  {
    id: "s1",
    name: "Springtouw Verstelbaar met Teller",
    price: 3.95,
    type: "sportengezondheid",
    image: generateProductImage("Springtouw", "06b6d4"),
    features: ["Digitale Teller", "Verstelbare Lengte", "Anti-slip Handvatten"],
    description:
      "Springtouw met digitale teller voor effectieve cardio training.",
    rating: 4.4,
    orders: 7234,
    discount: 45,
    originalPrice: 7.18,
    seller: "FitZone",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "s2",
    name: "Weerstandsbanden Set - 5 Stuks",
    price: 4.95,
    type: "sportengezondheid",
    image: generateProductImage("Weerstandsbanden", "f59e0b"),
    features: ["5 Weerstandsniveaus", "Latex Vrij", "Draagtas Inbegrepen"],
    description:
      "Complete set weerstandsbanden voor thuis sporten en kracht training.",
    rating: 4.5,
    orders: 9567,
    discount: 50,
    originalPrice: 9.9,
    seller: "HomeFit",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "s3",
    name: "Yoga Handdoek Anti-slip",
    price: 5.95,
    type: "sportengezondheid",
    image: generateProductImage("Yoga Handdoek", "8b5cf6"),
    features: ["Super Absorberend", "Snel Drogend", "Siliconen Noppen"],
    description: "Anti-slip yoga handdoek voor extra grip tijdens je workout.",
    rating: 4.3,
    orders: 5678,
    discount: 40,
    originalPrice: 9.92,
    seller: "YogaLife",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "s4",
    name: "Buikspier Roller Wieltje",
    price: 6.95,
    type: "sportengezondheid",
    image: generateProductImage("Roller", "ef4444"),
    features: ["Dubbel Wiel", "Kniebeschermer", "Stevige Handgrepen"],
    description: "Buikspierwiel voor effectieve core training thuis.",
    rating: 4.4,
    orders: 4567,
    discount: 35,
    originalPrice: 10.69,
    seller: "CoreTraining",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "s5",
    name: "Massage Bal met Noppen - 2 Stuks",
    price: 3.49,
    type: "sportengezondheid",
    image: generateProductImage("Massage Bal", "10b981"),
    features: ["Diepte Massage", "2 Maten", "Draagbaar"],
    description:
      "Massage ballen voor spierontspanning en triggerpointtherapie.",
    rating: 4.2,
    orders: 8901,
    discount: 55,
    originalPrice: 7.76,
    seller: "RelaxTools",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "s6",
    name: "Polsgewichten Set 2x 0.5kg",
    price: 4.49,
    type: "sportengezondheid",
    image: generateProductImage("Polsgewichten", "14b8a6"),
    features: ["Verstelbare Sluiting", "Zachte Vulling", "Reflecterend"],
    description:
      "Comfortabele polsgewichten voor extra weerstand tijdens je workout.",
    rating: 4.3,
    orders: 6234,
    discount: 50,
    originalPrice: 8.98,
    seller: "WeightPro",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
