/* Garden & Outdoor Products */

const gardenProducts = [
  {
    id: "g1",
    name: "Tuinhandschoenen met Anti-slip Coating",
    price: 2.49,
    type: "tuin",
    image: generateProductImage("Handschoenen", "10b981"),
    features: ["Anti-slip Palm", "Ademend", "Wasbaar"],
    description:
      "Comfortabele tuinhandschoenen met anti-slip coating voor alle klusjes.",
    rating: 4.3,
    orders: 8765,
    discount: 55,
    originalPrice: 5.53,
    seller: "GardenTools",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "g2",
    name: "Plant Waterzak Druppelsysteem - 4 Stuks",
    price: 4.95,
    type: "tuin",
    image: generateProductImage("Waterzak", "06b6d4"),
    features: ["4 Stuks", "Langzame Afgifte", "2L Capaciteit"],
    description:
      "Automatische plant waterzakken voor optimale water verdeling.",
    rating: 4.4,
    orders: 7654,
    discount: 50,
    originalPrice: 9.9,
    seller: "WaterSmart",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "g3",
    name: "Tuingereedschap Set - 9 Delige",
    price: 7.95,
    type: "tuin",
    image: generateProductImage("Gereedschap", "f59e0b"),
    features: ["9 Tools", "RVS Materiaal", "Ergonomische Handvatten"],
    description:
      "Complete tuingereedschap set met schep, hark, schoffel en meer.",
    rating: 4.5,
    orders: 6543,
    discount: 45,
    originalPrice: 14.45,
    seller: "GardenPro",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "g4",
    name: "Vogelhuis Hout met Ophanghaak",
    price: 8.95,
    type: "tuin",
    image: generateProductImage("Vogelhuis", "8b5cf6"),
    features: ["Natuurlijk Hout", "Weerbestendig", "Gemakkelijk Ophangen"],
    description: "Decoratief houten vogelhuis voor in de tuin of op balkon.",
    rating: 4.2,
    orders: 5432,
    discount: 40,
    originalPrice: 14.92,
    seller: "BirdHouse",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "g5",
    name: "Plantenlabels Waterproof - 100 Stuks",
    price: 2.95,
    type: "tuin",
    image: generateProductImage("Labels", "ec4899"),
    features: ["100 Stuks", "Waterproof", "Inclusief Marker"],
    description:
      "Waterdichte plantenlabels met marker voor overzicht in de tuin.",
    rating: 4.3,
    orders: 9876,
    discount: 60,
    originalPrice: 7.38,
    seller: "PlantTag",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "g6",
    name: "LED Tuinverlichting Solar - 8 Stuks",
    price: 6.95,
    type: "tuin",
    image: generateProductImage("Solar Lamp", "f59e0b"),
    features: ["8 Lampen", "Solar Powered", "Automatisch Aan/Uit"],
    description:
      "Solar tuinverlichting lampen voor sfeervolle verlichting zonder stroom.",
    rating: 4.4,
    orders: 11234,
    discount: 50,
    originalPrice: 13.9,
    seller: "SolarLight",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
