/* Fashion Products */

const fashionProducts = [
  {
    id: "f1",
    name: "Haarbandjes Elastisch - Set van 20",
    price: 1.95,
    type: "mode",
    image: generateProductImage("Haarbandjes", "ec4899"),
    images: [
      generateProductImage("Haarbandjes", "ec4899"),
      generateProductImage("20 Kleuren", "db2777"),
      generateProductImage("In Haar", "be185d"),
    ],
    features: ["Kleurrijk", "Schadevrij", "Verschillende Maten"],
    description: "Veelkleurige elastische haarbandjes voor alle haartypes.",
    rating: 4.2,
    orders: 16234,
    discount: 60,
    originalPrice: 4.88,
    seller: "BeautyBay",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "f2",
    name: "Sokken Unisex Katoen - 10 Paar",
    price: 5.95,
    type: "mode",
    image: generateProductImage("Sokken", "f59e0b"),
    images: [
      generateProductImage("Sokken", "f59e0b"),
      generateProductImage("10 Paar", "d97706"),
      generateProductImage("Kleuren Mix", "b45309"),
    ],
    features: ["Ademend Katoen", "Comfortabel", "Diverse Kleuren"],
    description:
      "Comfortabele katoenen sokken voor dagelijks gebruik, set van 10 paar.",
    rating: 4.3,
    orders: 9876,
    discount: 50,
    originalPrice: 11.9,
    seller: "SockStore",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "f3",
    name: "Scrunchies Fluweel - 12 Stuks",
    price: 2.49,
    type: "mode",
    image: generateProductImage("Scrunchies", "8b5cf6"),
    features: ["Fluweelachtig", "Haarvriendelij k", "12 Kleuren"],
    description: "Trendy fluwelen scrunchies in verschillende kleuren.",
    rating: 4.4,
    orders: 14567,
    discount: 65,
    originalPrice: 7.11,
    seller: "HairStyle",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "f4",
    name: "Zonnebril UV400 Bescherming",
    price: 3.95,
    type: "mode",
    image: generateProductImage("Zonnebril", "06b6d4"),
    features: ["UV400 Filter", "Lichtgewicht", "Diverse Stijlen"],
    description: "Stijlvolle zonnebril met volledige UV-bescherming.",
    rating: 4.1,
    orders: 8234,
    discount: 55,
    originalPrice: 8.78,
    seller: "SunShades",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "f5",
    name: "Crossbody Tas Klein Leer-Look",
    price: 7.95,
    type: "mode",
    image: generateProductImage("Tas", "ef4444"),
    features: ["Verstelbare Riem", "Meerdere Vakjes", "Kunstleer"],
    description:
      "Compacte crossbody tas met leren uitstraling voor je essentials.",
    rating: 4.5,
    orders: 6789,
    discount: 45,
    originalPrice: 14.45,
    seller: "BagShop",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "f6",
    name: "Sjaals Dames Zacht - 3 Stuks",
    price: 6.95,
    type: "mode",
    image: generateProductImage("Sjaals", "10b981"),
    features: ["Zachte Stof", "Lichtgewicht", "3 Designs"],
    description: "Set van 3 zachte en warme sjaals in verschillende kleuren.",
    rating: 4.3,
    orders: 5432,
    discount: 50,
    originalPrice: 13.9,
    seller: "WarmWear",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
