/* Baby & Kids Products */

const babyProducts = [
  {
    id: "bk1",
    name: "Baby Luiertasje Organizer",
    price: 4.95,
    type: "babykind",
    image: generateProductImage("Luiertasje", "ec4899"),
    images: [
      generateProductImage("Luiertasje", "ec4899"),
      generateProductImage("Vakjes Open", "db2777"),
      generateProductImage("Vol Gepakt", "be185d"),
    ],
    features: ["Compacte Opslag", "12 Vakjes", "Draagbaar"],
    description:
      "Handige luiertasje organizer voor onderweg met baby essentials.",
    rating: 4.4,
    orders: 10234,
    discount: 50,
    originalPrice: 9.9,
    seller: "BabyEssentials",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "bk2",
    name: "Babyslabbers Waterdicht - 10 Stuks",
    price: 5.95,
    type: "babykind",
    image: generateProductImage("Slabbers", "06b6d4"),
    images: [
      generateProductImage("Slabbers", "06b6d4"),
      generateProductImage("Kleuren Mix", "0891b2"),
      generateProductImage("Opvangbakje", "0e7490"),
    ],
    features: ["10 Stuks", "Waterdicht Siliconen", "Opvangbakje"],
    description:
      "Zachte waterdichte slabbers met opvangbakje voor minder morsen.",
    rating: 4.5,
    orders: 15678,
    discount: 55,
    originalPrice: 13.22,
    seller: "BabyMeal",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "bk3",
    name: "Nachtlampje Sterrenhemel Projector",
    price: 6.95,
    type: "babykind",
    image: generateProductImage("Nachtlampje", "8b5cf6"),
    images: [
      generateProductImage("Nachtlampje", "8b5cf6"),
      generateProductImage("Projectie", "7c3aed"),
      generateProductImage("Kleuren", "6d28d9"),
    ],
    features: ["Sterrenprojectie", "8 Kleuren", "USB Oplaadbaar"],
    description: "Magische sterrenhemel projector voor een rustige slaap.",
    rating: 4.6,
    orders: 18765,
    discount: 45,
    originalPrice: 12.64,
    seller: "SleepyStars",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "bk4",
    name: "Baby Haarborstel & Kam Set",
    price: 2.95,
    type: "babykind",
    image: generateProductImage("Haarborstel", "f59e0b"),
    images: [
      generateProductImage("Haarborstel", "f59e0b"),
      generateProductImage("Kam", "d97706"),
      generateProductImage("Set", "b45309"),
    ],
    features: ["Zachte Borstels", "Anti-statisch", "Ergonomisch"],
    description: "Zachte haarborstel en kam set speciaal voor babyhaar.",
    rating: 4.3,
    orders: 8765,
    discount: 60,
    originalPrice: 7.38,
    seller: "BabyCare",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "bk5",
    name: "Babysokjes Anti-slip - 12 Paar",
    price: 4.49,
    type: "babykind",
    image: generateProductImage("Babysokjes", "10b981"),
    images: [
      generateProductImage("Babysokjes", "10b981"),
      generateProductImage("Anti-slip Noppen", "059669"),
      generateProductImage("Alle Kleuren", "047857"),
    ],
    features: ["12 Paar", "Anti-slip Noppen", "Ademend Katoen"],
    description:
      "Kleurrijke babysokjes met anti-slip noppen voor eerste stapjes.",
    rating: 4.5,
    orders: 12345,
    discount: 55,
    originalPrice: 9.98,
    seller: "TinyFeet",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
  {
    id: "bk6",
    name: "Speelgoednet Badkamer met Zuignappen",
    price: 3.49,
    type: "babykind",
    image: generateProductImage("Speelgoednet", "ef4444"),
    images: [
      generateProductImage("Speelgoednet", "ef4444"),
      generateProductImage("Met Speelgoed", "dc2626"),
      generateProductImage("Gemonteerd", "991b1b"),
    ],
    features: ["Sneldrogend Mesh", "Sterke Zuignappen", "Groot Formaat"],
    description: "Handig opbergnet voor badspeelgoed met sterke zuignappen.",
    rating: 4.2,
    orders: 9876,
    discount: 50,
    originalPrice: 6.98,
    seller: "BathToys",
    shipFrom: "CN",
    freeShip: true,
    local: false,
  },
];
